<a href="https://colab.research.google.com/github/vyragosa/Deep-Learning-with-Pytorch/blob/main/Homework1/Seminar1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import torch

# Задача 2. Cделать нейрон, соответствующий оператору НЕ.

In [40]:
class Neuron(torch.nn.Module):
	def __init__(self):
		super().__init__()
		self.fc = torch.nn.Linear(1, 1)

	def forward(self, x):
		return torch.heaviside(self.fc(x), torch.tensor([0.]))

In [41]:
neuron = Neuron()
neuron.fc.weight, neuron.fc.bias

(Parameter containing:
 tensor([[-0.5958]], requires_grad=True), Parameter containing:
 tensor([-0.4020], requires_grad=True))

In [42]:
neuron.fc.weight.data = torch.tensor([[-1.]])
neuron.fc.bias.data = torch.tensor([1.])

In [45]:
x = torch.tensor([[0.],
                  [1.],])
neuron(x)

tensor([[1.],
        [0.]], grad_fn=<NotImplemented>)

# Задача 3. Cделать нейрон, соответствующий оператору И.

In [9]:
class Neuron(torch.nn.Module):
  def __init__(self):
    super().__init__()
    self.fc = torch.nn.Linear(2, 1)

  def forward(self, x):
    return torch.heaviside(self.fc(x), torch.tensor([0.]))

In [10]:
neuron = Neuron()
neuron.fc.weight, neuron.fc.bias

(Parameter containing:
 tensor([[-0.1682, -0.1875]], requires_grad=True), Parameter containing:
 tensor([-0.0911], requires_grad=True))

In [11]:
neuron.fc.weight.data = torch.tensor([[1., 1.]])
neuron.fc.bias.data = torch.tensor([-1.])

In [13]:
x = torch.tensor([[0., 0.],
                  [0., 1.],
                  [1., 0.],
                  [1., 1.],])
neuron(x)

tensor([[0.],
        [0.],
        [0.],
        [1.]], grad_fn=<NotImplemented>)

# Задача 4. Cделать нейрон, соответствующий оператору ИЛИ.

In [14]:
class Neuron(torch.nn.Module):
  def __init__(self):
    super().__init__()
    self.fc = torch.nn.Linear(2, 1)

  def forward(self, x):
    return torch.heaviside(self.fc(x), torch.tensor([0.]))

In [15]:
neuron = Neuron()
neuron.fc.weight, neuron.fc.bias

(Parameter containing:
 tensor([[0.4567, 0.1658]], requires_grad=True), Parameter containing:
 tensor([-0.0649], requires_grad=True))

In [16]:
neuron.fc.weight.data = torch.tensor([[1., 1.]])
neuron.fc.bias.data = torch.tensor([0.])

In [17]:
x = torch.tensor([[0., 0.],
                  [0., 1.],
                  [1., 0.],
                  [1., 1.],])
neuron(x)

tensor([[0.],
        [1.],
        [1.],
        [1.]], grad_fn=<NotImplemented>)

# Задача 5. Cделать нейрон, соответствующий оператору XOR.

In [18]:
class Neuron(torch.nn.Module):
  def __init__(self):
    super().__init__()
    self.fc = torch.nn.Linear(2, 1)

  def forward(self, x):
    return torch.heaviside(self.fc(x), torch.tensor([0.]))

In [27]:
neuron1 = Neuron()
neuron1.fc.weight.data = torch.tensor([[1., -1.]])
neuron1.fc.bias.data = torch.tensor([0.])

In [28]:
neuron2 = Neuron()
neuron2.fc.weight.data = torch.tensor([[-1., 1.]])
neuron2.fc.bias.data = torch.tensor([0.])

In [29]:
neuron3 = Neuron()
neuron3.fc.weight.data = torch.tensor([[1., 1.]])
neuron3.fc.bias.data = torch.tensor([0.])

In [37]:
x = torch.tensor([[0., 0.],
                  [0., 1.],
                  [1., 0.],
                  [1., 1.],])

neuron3(torch.cat((neuron1(x), neuron2(x)), 1))

tensor([[0.],
        [1.],
        [1.],
        [0.]], grad_fn=<NotImplemented>)